# name: UI Tests

# on: [push]

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup server
#         working-directory: ./server
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install
#       - run: node src/index.js
#       - name: Cypress run
#         working-directory: ./client
#         uses: cypress-io/github-action@v2
#         with:
#           build: npm test
name: Test App

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.2.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run API in background
        working-directory: server
        run: |
          npm install
          npm start &
        env:
          CI: true

      - name: Run and test app
        working-directory: client
        run: |
          npm install
          npm build
          npm start &
          npm run cypress:run
        env:
          CI: true
        #   API_URI: http://localhost:4000/graphql
