name: Test App

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.2.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run API in background
        working-directory: server
        run: |
          npm install
          npm start &

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          build: npm run build
          start: npm start
