name: Cypress Tests

on: [push]

jobs:
  cypress_tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: testing

    strategy:
      matrix:
        node-version: [14.9.x]

    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - uses: getong/elasticsearch-action@v1.2
        with:
          elasticsearch version: '7.6.1'
          host port: 9200
          container port: 9200
          host node port: 9300
          node port: 9300
          discovery type: 'single-node'

      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run API in background
        working-directory: server
        run: |
          npm install
          npm start &
        env:
          NODE_ENV: production
          PORT: 4000
          SOCKET_PORT: 4001
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          MONGO_ATLAS_URI: ${{ secrets.MONGO_ATLAS_URI }}
          # TOKEN_SECRET: serviciosyaapitoken
          # MONGO_ATLAS_URI: mongodb+srv://agustin:tpttads@cluster0.f7x6o.mongodb.net/tp-database?retryWrites=true&w=majority

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          start: npm start
          wait-on: 'http://localhost:4200'
